<a href="https://colab.research.google.com/github/VitikaJain25/Eduxlabs-AI-ML/blob/main/eict_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python Libraries for Data Science**
* Numpy
* Pandas
* Matplotlib

In [1]:
#Numpy - Numerical Python - We use it for numerical calculations.

a = 17
b = 2

print(a*b)

34


In [ ]:
# We can do calculation as done above (without numpy). Than why we need numpy??

In [2]:
# Getting error.

l1 = [2,3,4,5,6]
b = 2

print(l1 * b)
print(l1 / b)

[2, 3, 4, 5, 6, 2, 3, 4, 5, 6]


TypeError: ignored

In [6]:
# Not getting error.

import numpy as np
n1 = np.array([2,3,4,5,6])
b = 2

print(n1 * b)
print(n1 / b)

[ 4  6  8 10 12]
[1.  1.5 2.  2.5 3. ]


In [7]:
# If we put as a list, it converts to 1D as list cannot capture multi dimentional array.
l2 = [[6,8,9,2],[4,5,7,1]]
print(l2)

[[6, 8, 9, 2], [4, 5, 7, 1]]


In [8]:
# If we capture in numpy array, it will capture as in the same form(2D in this case).
# Numpy can handle multi dimentional array.

n2 = np.array([[6,8,9,2],[4,5,7,1]])
print(n2)

[[6 8 9 2]
 [4 5 7 1]]


In [9]:
print(n2.ndim)
print(n2.shape)
print(n2.size)

2
(2, 4)
8


In [11]:
print(np.sum(n2))
print(np.prod(n2))
print(np.mean(n2))
print(np.min(n2))
print(np.max(n2))
print(np.std(n2))
print(np.var(n2))
print(np.argmin(n2))
print(np.argmax(n2))

42
120960
5.25
1
9
2.6339134382131846
6.9375
7
2


In [12]:
print(n2)

[[6 8 9 2]
 [4 5 7 1]]


In [13]:
# Axis value can be 0 or 1
# Axis = 1 - It will perform calculations for each row
# Axis = 0 - It will perform calculations for each column

print(np.sum(n2, axis = 1))
print(np.prod(n2, axis = 1))
print(np.mean(n2, axis = 1))
print(np.min(n2, axis = 1))
print(np.max(n2, axis = 1))
print(np.std(n2, axis = 1))
print(np.var(n2, axis = 1))
print(np.argmin(n2, axis = 1))
print(np.argmax(n2, axis = 1))

[25 17]
[864 140]
[6.25 4.25]
[2 1]
[9 7]
[2.68095132 2.16506351]
[7.1875 4.6875]
[3 3]
[2 2]


In [14]:
# Axis = 0 - It will perform calculations for each column

print(np.sum(n2, axis = 0))
print(np.prod(n2, axis = 0))
print(np.mean(n2, axis = 0))
print(np.min(n2, axis = 0))
print(np.max(n2, axis = 0))
print(np.std(n2, axis = 0))
print(np.var(n2, axis = 0))
print(np.argmin(n2, axis = 0))
print(np.argmax(n2, axis = 0))

[10 13 16  3]
[24 40 63  2]
[5.  6.5 8.  1.5]
[4 5 7 1]
[6 8 9 2]
[1.  1.5 1.  0.5]
[1.   2.25 1.   0.25]
[1 1 1 1]
[0 0 0 0]
